apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: tempo
      version: "1.24.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  targetNamespace: monitoring
  values:
    tempo:
      reportingEnabled: false
      metricsGenerator:
        enabled: false
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
    nodeSelector:
      kubernetes.io/hostname: savior-6fc31951
    persistence:
      enabled: true
      size: 10Gi
    service:
      type: ClusterIP
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
