apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hami
  namespace: hami-system
spec:
  interval: 1h
  chart:
    spec:
      chart: hami
      sourceRef:
        kind: HelmRepository
        name: hami-charts
        namespace: flux-system
      version: 2.8.0
  valuesFrom:
    - kind: ConfigMap
      name: hami-values
