apiVersion: v1
kind: Service
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: harbor-registry
  ports:
    - name: http
      port: 5000
      targetPort: http
      nodePort: 32000
