apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fake-gpu-operator
  namespace: gpu-operator
spec:
  interval: 1h
  url: oci://ghcr.io/run-ai/fake-gpu-operator
  type: oci
