apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-gpu-operator-values
  namespace: gpu-operator
data:
  values.yaml: |
    topology:
      nodePools:
        savior:
          gpuProduct: NVIDIA-H100
          gpuCount: 2
          gpuMemory: 81920
        thinker:
          gpuProduct: NVIDIA-H200
          gpuCount: 3
          gpuMemory: 143360
      nodePoolLabelKey: run.ai/simulated-gpu-node-pool

    environment:
      resourceReservationNamespace: kai-resource-reservation

    devicePlugin:
      enabled: false

    statusUpdater:
      disableNodeLabeling: true

    kwokGpuDevicePlugin:
      enabled: false

    kwokDraPlugin:
      enabled: true

    runtimeClass:
      enabled: false

    draPlugin:
      enabled: true
