apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: fake-gpu-operator
    namespace: gpu-operator
  install:
    createNamespace: false
  valuesFrom:
    - kind: ConfigMap
      name: fake-gpu-operator-values
