apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ocirepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: fake-gpu-operator-values
    namespace: gpu-operator
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
