topology:
  nodePools:
    default:
      gpuProduct: Tesla-K80
      gpuCount: 8
      gpuMemory: 11441
  nodePoolLabelKey: run.ai/simulated-gpu-node-pool

statusUpdater:
  disableNodeLabeling: true

draPlugin:
  enabled: true
  kubeletPlugin:
    nodeSelector:
      nvidia.com/gpu.deploy.device-plugin: "true"
