apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 1
  storage:
    size: 8Gi
  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: postgres-app
