apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 10m
  chart:
    spec:
      chart: redis
      version: "23.2.12"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      enabled: true
      password: mysecurepassword
    master:
      persistence:
        enabled: true
        size: 2Gi
