apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  interval: 5m
  chartRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: OCIRepository
    name: telepresence-oss
    namespace: ambassador
  valuesFrom:
    - kind: ConfigMap
      name: traffic-manager-values
      valuesKey: values.yaml
