apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  interval: 5m
  chart:
    spec:
      chart: telepresence-oss
      sourceRef:
        kind: OCIRepository
        name: telepresence-oss
        namespace: ambassador
      # Pin the Helm chart version to match the Telepresence client.
      version: v2.25.0
  valuesFrom:
    - kind: ConfigMap
      name: traffic-manager-values
      valuesKey: values.yaml
