apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  interval: 5m
  chart:
    spec:
      chart: telepresence
      version: "2.25.0"
      sourceRef:
        kind: HelmRepository
        name: telepresence-oss
        namespace: ambassador
  valuesFrom:
    - kind: ConfigMap
      name: traffic-manager-values
      valuesKey: values.yaml
