apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
spec:
  interval: 10m
  chart:
    spec:
      chart: kafka
      version: "32.4.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
      replicaCount: 3
      persistence:
        enabled: true
        size: 10Gi
      service:
        type: ClusterIP
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
      image:
        repository: bitnamilegacy/kafka
        tag: latest # ✅ set your working image tag here
        pullPolicy: IfNotPresent
