apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 15.2.2  # <-- pick a stable version from Bitnami's repo
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  targetNamespace: database
  values:
    auth:
      username: appuser
      database: appdb
      existingSecret: postgres-auth
    primary:
      persistence:
        size: 8Gi
    volumePermissions:
      enabled: true
