apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  targetNamespace: database
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    auth:
      username: appuser
      database: appdb
      existingSecret: postgres-auth   # Passwords delivered via Secret manifest.
    primary:
      persistence:
        size: 8Gi
    volumePermissions:
      enabled: true
