apiVersion: v1
kind: ConfigMap
metadata:
  name: sciflow-config
  namespace: sciflow
data:
  RUST_LOG: info,tower_http=info
  POD_NAMESPACE: sciflow
  PUBLIC_BASE_URL: https://master161.yuanwuzhi.io/sciflow
  IMAGE_REGISTRY_HOST: localhost:32000
  REGISTRY_BASE_URL: http://registry-v2.harbor.svc.cluster.local:5000
  IMAGE_OPERATION_WORKER_IMAGE: ghcr.io/yuanwuzhi/sciflow-image-worker:sha-81c50d071b23
  IMAGE_WORKER_EXECUTION_MODE: nerdctl
  IMAGE_WORKER_RUNTIME_CLI: nerdctl --address /run/k3s/containerd/containerd.sock -n k8s.io
  IMAGE_WORKER_CONTAINERD_SOCKET_PATH: /run/k3s/containerd/containerd.sock
  IMAGE_WORKER_INSECURE_REGISTRY: "true"
  IMAGE_WORKER_REGISTRY_AUTH_SECRET_NAME: sciflow-registry-auth
  AUTH_HEADER_USER: x-auth-request-preferred-username
  AUTH_HEADER_EMAIL: x-auth-request-email
  AUTH_HEADER_GROUPS: x-auth-request-groups
  AUTH_HEADER_SUBJECT: x-auth-request-user
  AUTHENTIK_BASE_URL: https://master161.yuanwuzhi.io/authentik
  AUTHENTIK_API_URL: http://authentik-server.authentik.svc.cluster.local/authentik/api/v3
  STORAGE_WORKSPACE_ROOT: /var/lib/sciflow-storage/workspaces
  STORAGE_SHARED_ROOT: /var/lib/sciflow-storage/shared
  INSTANCE_WORKSPACE_VOLUME_SOURCE: pvc
  INSTANCE_WORKSPACE_PVC_NAME: sciflow-storage
  INSTANCE_WORKSPACE_MOUNT_PATH: /workspace
  INSTANCE_WORKSPACE_SUBPATH_PREFIX: workspaces
  INSTANCE_SHARED_VOLUME_SOURCE: pvc
  INSTANCE_SHARED_PVC_NAME: sciflow-storage
  INSTANCE_SHARED_MOUNT_PATH: /share
  INSTANCE_SHARED_SUBPATH: shared
  INSTANCE_SYSTEM_VOLUME_SOURCE: pvc
  INSTANCE_SYSTEM_PVC_NAME: sciflow-storage
  INSTANCE_SYSTEM_MOUNT_PATH: /.sciflow
  INSTANCE_SYSTEM_SUBPATH: .sciflow
