apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - storage-pvc.yaml
  - storage-bootstrap.yaml
  - gateway.yaml
  - orchestrator-api.yaml
  - orchestrator-controller.yaml
  - policy.yaml
  - images.yaml
  - operations.yaml
  - reporting.yaml
  - middlewares.yaml
  - ingresses.yaml
images:
  - name: ghcr.io/yuanwuzhi/sciflow-gateway
    newTag: sha-a55d2b2475e3
  - name: ghcr.io/yuanwuzhi/sciflow-images
    newTag: sha-bf20cb0a278b
  - name: ghcr.io/yuanwuzhi/sciflow-operations
    newTag: sha-bf20cb0a278b
  - name: ghcr.io/yuanwuzhi/sciflow-orchestrator-api
    digest: sha256:03630a3ceca18aa253c05dbc225b95b14ace44dd5e1bd3bc269dee757343390c
  - name: ghcr.io/yuanwuzhi/sciflow-orchestrator-controller
    digest: sha256:ff95a8e2b904079f6bb83e574b5d8926a5b8c4b290a46c90d068b18c3855cc12
  - name: ghcr.io/yuanwuzhi/sciflow-policy
    newTag: sha-a55d2b2475e3
  - name: ghcr.io/yuanwuzhi/sciflow-reporting
    newTag: sha-526b625296f0
