apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - gateway.yaml
  - orchestrator.yaml
  - policy.yaml
  - images.yaml
  - operations.yaml
  - reporting.yaml
  - localhost-middleware.yaml
  - localhost-ingress.yaml
