apiVersion: apps/v1
kind: Deployment
metadata:
  name: sciflow-orchestrator-controller
  namespace: sciflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orchestrator-controller
      app.kubernetes.io/part-of: sciflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orchestrator-controller
        app.kubernetes.io/part-of: sciflow
    spec:
      serviceAccountName: sciflow-orchestrator
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: sciflow-storage
          persistentVolumeClaim:
            claimName: sciflow-storage
      containers:
        - name: orchestrator-controller
          image: ghcr.io/yuanwuzhi/sciflow-orchestrator-controller
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: sciflow-config
            - secretRef:
                name: sciflow-db
          env:
            - name: CONTROLLER_DEBUG_ENDPOINTS_ENABLED
              value: "true"
          volumeMounts:
            - name: sciflow-storage
              mountPath: /var/lib/sciflow-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sciflow-orchestrator
  namespace: sciflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sciflow-orchestrator
  namespace: sciflow
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["sciflow.ai"]
    resources: ["sciflowinstances"]
    verbs: ["create", "get", "list", "watch", "patch", "delete"]
  - apiGroups: ["sciflow.ai"]
    resources: ["sciflowinstances/status"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sciflow-orchestrator
  namespace: sciflow
subjects:
  - kind: ServiceAccount
    name: sciflow-orchestrator
    namespace: sciflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sciflow-orchestrator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sciflow-orchestrator
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sciflow-orchestrator
subjects:
  - kind: ServiceAccount
    name: sciflow-orchestrator
    namespace: sciflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sciflow-orchestrator
