apiVersion: v1
kind: Secret
metadata:
  name: sciflow-images-db
  namespace: sciflow
type: Opaque
stringData:
  DATABASE_URL: postgres://appuser:change-me@postgres-rw.database.svc.cluster.local:5432/appdb
---
apiVersion: v1
kind: Secret
metadata:
  name: sciflow-operations-db
  namespace: sciflow
type: Opaque
stringData:
  DATABASE_URL: postgres://appuser:change-me@postgres-rw.database.svc.cluster.local:5432/appdb
