apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-config
  namespace: cloudflare-tunnel-ingress-controller
stringData:
  apiToken: ENC[AES256_GCM,data:0zzcoMg1OTRTcKQ5vQhjMSW4+TAZyxJw63VKVKBxz3gFhQwZ7X5GkQ==,iv:CvzhmB++tuGwE7hHTPxrpj15KrS0sUzEG4eAEHmchMo=,tag:a5bmYxPsTS4TLGJZijVzbw==,type:str]
  accountId: ENC[AES256_GCM,data:xqRQ1tE3oJfa9bEMYGI91RDOT1DqhXnQvsKxg1hBeck=,iv:Y1x9CAz3p8Uov5OMbdtVQyF1zKXhfHMbhtNHw+q3w0Y=,tag:izi4PQ0/aOcg31Ps8SU7Qw==,type:str]
  tunnelName: ENC[AES256_GCM,data:WESepkaaAQ==,iv:irVSY/Ef0XlSiBjFr8X2tFhMbJ7Rm6n1Bukgw7ePVV4=,tag:1xwW38c0R/ywCWeDY5PqGA==,type:str]
sops:
  age:
    - recipient: age16sycmn5ytsx2lwxa2c8t2q8t0e3mecks8xxxc4n6kctf4arqhvmse9ms65
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRlVNTDIxZU82a003T0JP
        bjA3czZBNHNQSXlBSnhramdVRTUvV2dTZ1FrCkR3V2s4UkxaY3lNUCtxYnh3aWxZ
        WGNKQ253LzI5cmhmb0xtcTQrVVZBUVEKLS0tIEtoazk5bSthUjQyc3pjalBpZnZN
        b1RrQXVwUFBRZ0ttU1Y5T2ZiOEtiRDgKD8L6gPqnvHOsSKA+OE++8QlwVg9wXkaE
        UdZ/FU9MSCfozsc3jp0HHUP8aj+OmGk07bd/bHY7ZuBTTT++eyI+ow==
        -----END AGE ENCRYPTED FILE-----
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPrKOulE9FoU7e91jMcLU6HnlaIRtv7tR1XPUSI8qNeG
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHhCTTd4USBIVWRX
        VjNPZjJuekxLb2VvdjJIeFMvSUorOXhnVTFWVXdJSkNVOXNaVUM4CmRZZlBtcDRI
        UE95VXo1RER6QTc5bHZYOFRsaHpwMk9wcm5HNWJPSC9OTTgKLS0tIEhGWGdzalds
        Qk1wVGhBQkc4TlhsK1BiTUdLWjFzQTNueFdhTENmbEY4YTAKdhR4P0gKX2TG+6pD
        zfAtBltB/gIzp5+17pMoifvvq9RWs8q4WwwcgxkBPLnG7HpJjodGvVcnHP+anp4G
        j2DMrw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJrWwGk9L6aGeJUflLOY25e7Aaa/AfDU51irnmchw1Zw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDhNMWo1dyBzYUhP
        QzQzbkQxY1BTTTgydGdjeU5SQWJaZjF1bTAxRmpEZUtxK0g1OGtvCnZRci80TUw5
        L283b3kwVGVBK2tyTXFZRlRyN2dIa0I5cVZyK2VsQm0rNkUKLS0tIEkzQTBUSUI5
        VG5FaGQ2YmVnSFA3OXBiSW8rcUo2ak0xSFg5Q0NTQnRESmsKy3RjIKlytk0iG+MA
        7cFomwBvHT/xTF6LGsb77m76Pql6u58q6mnLZzsdpzndbvAQ7ay+vF2ab8byOCB4
        siUK1A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1d70rqqctcsqn3jcnffvszjwcjvpjezrtv88msj07te7dyhzhqy5s4jh87z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d1pRR21NTFJ6RU5oenky
        MFBzM1Z6TlppNSthZWNXLzVGT0p4UUk4eEh3CnNTbm50cksxeFNTSkJnRmRaemxn
        K0FZajNaL1UvU0dqVHlRa1lFMUlUcVkKLS0tIGZWdnp6OFpQc0JCUEF2K0xWQzdB
        emlhUmFlRkRLQlRBeUc2c0tmRzBseEkKJG0yVQTe8sX3AOgbLMya4wYyNVYa54AW
        mJHD9nBq8EAViWcyb2jsBROZ4nxtsJ1HQsvKjdjIC52S/zNvOGL01Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-01T03:05:55Z"
  mac: ENC[AES256_GCM,data:kSfi4opAEY+7gw6LaedVOblxmwicXVp62AR5Qd60dz46uXQkyXimD0kiyLilpIJ3XDM9ghmnGcIcbPJWA63MjgDDaaXqmbcyqLwolIrZp+gPFDs63f0xQCx7UPC0cKTFLJ/emrfWkC7KDuRBARRnZ3h9awtmjPuTNQZ5GVJkiWg=,iv:4tnfLcSGS6KjwlaChpvjeMiQ5VVhwD9HdkNtqiDTyb0=,tag:v9XKltZ7CvgwudPTV4PK8w==,type:str]
  encrypted_regex: ^(cloudflare|data|stringData)$
  version: 3.11.0
