apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - grafana-oauth-secret.yaml
  - harbor-oauth-secret.yaml
  - grafana-blueprint-configmap.yaml
  - harbor-blueprint-configmap.yaml
  - oauth2-proxy-browser-blueprint-configmap.yaml
  - self-service-blueprint-configmap.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - localhost-ingress.yaml
