apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-localhost
  namespace: authentik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.priority: "90"
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - path: /authentik
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
    - host: authentik.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
    - host: authentik.100.124.90.107.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
